version: '3'
services:

  #PHP Service
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    image: server
    user: root
    container_name: server
    restart: unless-stopped
    tty: true
    ports:
    - "8080:8080"
    links:
      - db:mysql
    environment:
      SERVICE_NAME: python
      SERVICE_TAGS: dev
    working_dir: /var/www/python
    volumes:
    - ./:/var/www/python
    networks:
    - app-network


  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - /var/docker/mysql:/var/lib/mysql/
    networks:
    - app-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
